# -*- coding: utf-8 -*-
"""Image Processing 11 Jan 2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-TfEKi4kP3yI94qotgljLIfEKwiB4KzD
"""

from skimage.io import imread
A = imread('image_01.png')
print(type(A))
print(A.shape)

from matplotlib.pyplot import imshow
imshow(A)

A

from skimage.io import imread
B = imread('image_01.png', as_gray=True)
print(type(B))
print(B.shape)

from matplotlib.pyplot import imshow
imshow(B)

B

from numpy import savetxt
savetxt('test.csv',A)

A_red = A[:,:,0]
print(A_red.shape)

A_green = A[:,:,1]
print(A_green.shape)

A_blue = A[:,:,2]
print(A_blue.shape)

from numpy import savetxt

savetxt('red.xlsx',A_red)
savetxt('green.xlsx',A_green)
savetxt('blue.xlsx',A_blue)

A_red

